### ISSUE TITLE
常用最大ブレーキとEBの判定が逆になってしまう

### ISSUE THREAD

**Issue by unlock-51071F** [kusaanko/BveNumerousControllerInterface#10]
MTCのP4-B7/P5-B5カセット使用時において、EBの一つ前の段に入れると非常ブレーキ判定になってしまうようです。
(P4-B7カセットの場合B7、P5-B5カセットの場合B5のときです)
逆にEB段に入れると、各カセットの常用最大ブレーキ判定になります。
USBのポートを変えたりハブを挟んだりしても変化ありませんでした。

ドライバはZadigを用いてWinUSB(v6.1.7600.16385)を割り当てています。

BVEのバージョンは5.8、入力プラグインのバージョンは0.6を使用しています。

**Comment by kusaanko** [comment]
報告ありがとうございます。
私はMTCを所持していないため動作確認ができていない状況になっています。
そこで、デバッグ用にプラグインを作ったのでそちらで表示された数字を教えてもらえないでしょうか。
おそらく、ノッチを切り替えるとダイアログが出てきて「MultiTrainController 数字」が出てくるはずです。その時のカセット、ノッチ、数字を教えていただきたいです。
プログラム自体は動作未確認ですのでこの通りには動かないかもしれません。その時は教えて下さい。
[Kusaanko.NumerousControllerInterface.dll.zip](https://github.com/kusaanko/BveNumerousControllerInterface/files/7453683/Kusaanko.NumerousControllerInterface.dll.zip)

**Comment by unlock-51071F** [comment]
報告が遅れてしまい申し訳ありません。以下が結果です。

[ P4-B7カセット ]
EB: 0,1
B7: 0,2
B6: 0,3
B5: 0,4
B4: 0,5
B3: 0,6
B2: 0,7
B1: 0,8
N : 0,9
P1: 0,10
P2: 0,11
P3: 0,12
P4: 0,13

[ P5-B5カセット ]
EB: 1
B5: 2
B4: 3
B3: 4
B2: 5
B1: 6
N : 7
P1: 8
P2: 9
P3: 10
P4: 11
P5: 12

[ P4-B6カセット ]
EB: 1
B7: 2
B6: 3
B5: 4
B4: 5
B3: 6
B2: 7
N : 8
P1: 9
P2: 10
P3: 11
P4: 12

[ P5-B8カセット ]
Zadigでドライバを当てても認識しませんでした。

**Comment by kusaanko** [comment]
貴重なデータありがとうございます。
データをもとに修正しました。こちらはどうでしょうか。
[Kusaanko.NumerousControllerInterface.dll.zip](https://github.com/kusaanko/BveNumerousControllerInterface/files/7462504/Kusaanko.NumerousControllerInterface.dll.zip)

**Comment by unlock-51071F** [comment]
お送りいただいたプラグインで確認しましたところ、
・P4-B8カセットは各段数の間にB7判定が出る/力行に入れても反応がない
・P5-B5カセットは今までと変わらずEBと常用最大が逆
という結果になりました。

上手く説明できる自信がありませんので勝手ながら動画も添付させていただきます…。
https://youtu.be/o4EFRkccl3Y

**Comment by kusaanko** [comment]
ご丁寧にありがとうございます。
一瞬B7が出るバグ、EB関係のバグがこれで修正されると思います。EBはあまり自信がありませんが...ついでに力行も反応するようになってないかな、という感じの修正です。よろしくおねがいします。
[Kusaanko.NumerousControllerInterface.dll.zip](https://github.com/kusaanko/BveNumerousControllerInterface/files/7465053/Kusaanko.NumerousControllerInterface.dll.zip)

**Comment by unlock-51071F** [comment]
お送りいただいたプラグインで正常な動作が確認できました！
P5-B8は認識しませんでしたが、P4-B7/P4-B6/P5-B5カセットについてはノッチ段数やキー割り当て等すべて正常に動作しました。
ご多忙のところ、バグの対応いただきありがとうございました。

**Comment by kusaanko** [comment]
よかったです。ご協力ありがとうございました。0.7としてこちらのバグ修正したものをリリースしておきます。
