### ISSUE TITLE
複数コントローラーの併用について

### ISSUE THREAD

**Issue by SkipWalker731** [kusaanko/BveNumerousControllerInterface#12]
複数のコントローラーを併用し、一つは力行用・一つは制動用というようにプロファイルを設定し操作できるようにすることは可能でしょうか。
当方下記リンクのコントローラーを入手しまして、コンピュータの入力がスティックとレバーでそれぞれ分かれており、片方ずつ使用するときは問題ないのですが、両方を同時に選択することはできません。この二つを力行・制動のそれぞれに用いることはできないかと考えております。
https://www.thrustmaster.com/ja-ja/products/tca-sidestick-airbus-edition/

**Comment by kusaanko** [comment]
力行・制動・力行制動を持たないコントローラー全て別々で用意して使えるようにはしてあります！
力行を持つコントローラーが複数あるとか、制動を持つコントローラーが複数あるとかだと競合してしまうのでどれを使うかを聞くダイアログが出てくるようになっています
ただコントローラー設定画面がまだ不安定な動作をすることがあるのでそちらのコントローラーの設定がうまくいくかどうか...はよくわかりません
不具合ありましたらまたこちらに書いていただければ対応します

それともう一つ懸念点としては"同じコントローラーが二つ"ですね
現在コントローラーの識別は「コントローラー名」で行っているので（コントローラー名以外に識別できる要素がなかったので、ここはかなり迷いましたがコントローラー名での識別を未だ採用しています）
コントローラー名とプロファイルを紐づけているので同じコントローラー名だと別々に用意するのはできないと思います
もし同じ名前でしたらデバイスマネージャー上でデバイス名を変更して重複しないようにすればコントローラー名を変えられたりするんでしょうか？その辺りは試したことがないので未知の領域です
ただこの同じ名前のコントローラーが複数というシナリオはよくあると思うのでどうにか対応はしたいと考えています

**Comment by kusaanko** [comment]
もしかしたらデバイス名の変更というのは [Zadig](https://zadig.akeo.ie) を使えばできるかもですね
Zadigでドライバを当てる時にデバイス名を変えられるのでそれでなんとかなったりするかもです

**Comment by SkipWalker731** [comment]
両方のコントローラーはそれぞれ別の名前で登録されてます。
最初に懸念なさっていたように、どうやら中立位置で逆側の値が入力されていて、それが競合しているみたいです(なんなら両方のコントローラーが設定していない軸に制動・力行が当てられている…？)
何度再設定してもスティックには左に倒すと制動が、レバーの方は制動の切位置より下げると力行が入るみたいです…🤔
![制動中立](https://github.com/user-attachments/assets/039cfa35-9ade-4dc1-a8dc-1fedc98e5cfb)
![制動非常](https://github.com/user-attachments/assets/387ff9cf-b5db-45a0-9859-a4e4ae861334)

![力行中立](https://github.com/user-attachments/assets/845502c0-5414-4b02-922c-92a5a07d5134)
![力行全ノッチ](https://github.com/user-attachments/assets/733f6086-7ddf-4e3a-bcf3-2f5dc74b8489)
![力行(なぜかY軸に制動が割り当てられている)](https://github.com/user-attachments/assets/3fc6549f-a195-41c7-8614-fc7b1b22188f)

**Comment by SkipWalker731** [comment]
検証したところ、左レバーが制動、スティックの手前引きが力行としたところ、右レバーは力行、スティックの左倒しは制動がかかるみたいです。右レバーの力行がノッチ6段の2段位置、スティックの制動が2段位置にかかります。
軸設定時に右レバーを入力信号での中立位置に置き、左レバーを制動、スティックの手前引きを力行にしたところ、スティックを奥に倒すとワンハンドルマスコンと同じ挙動で制動に入りました。このとき、スティックの制動は中立位置で9段中2段位置になります。

**Comment by SkipWalker731** [comment]
制動に使うレバーが値-1000〜443、力行のスティックは0〜1000になっています。
コントローラーの入出力の値は本当にど素人なのですが、それぞれの値がそのまま制動〜力行の-1000〜1000の値に対応して処理されるためでしょうかね…？(言語化があやしい)

**Comment by kusaanko** [comment]
コントローラーの状態が見れると思いますので
https://gkumasan.com/how-to-controller-test-on-pc/
これで実際どのような入力がされているかを見ていただいて、その動きを教えていただければ何かわかるかもしれません

**Comment by SkipWalker731** [comment]
解決しました。
お教えいただいた通りに確認したところ、スティックがX/Y/Z軸、レバーがX/Y軸と名称が被っているために値が混同されていたようです。メーカー製のツールでレバー側の軸名を被らないものに変更するプロファイルを作成したところ、想定通りスティックは力行のみ、レバーは制動のみにかかるようになりました。
お忙しいところ対応いただきありがとうございました。

**Comment by kusaanko** [comment]
無事動いたみたいでよかったです！
また何かありましたら再度オープンしてください

**Comment by SkipWalker731** [comment]
それと、Issueのタイトルと異なるのですが、ボタン割当をしていたところ「定速運転」が「低速運転」と表示されておりましたので、もしお時間がございましたら訂正の方をお願いいたします。

**Comment by kusaanko** [comment]
変換ミスですかね...
修正までリオープンしておきます
ご報告ありがとうございます！
